### PR TITLE
Updating to Collections.abc Iterable

### PR DESCRIPTION
**Pull request by svirgilgood**
* Python 3.10 moves `collections.Iterator` to `collections.abc.Iterable`
* These changes were added in the different files cause ninjaaron is a dork
* Updating the files as needed. Now it works.

### CODE REVIEW

**Comment by ninjaaron** [comment]
An [iterator](https://docs.python.org/3/glossary.html#term-iterator) and an iterable are two different concepts. Every iterable may be reduced to an iterator, but it's structure may not necessarily be sequential (a dictionary is an obvious example). This code is intended for handling sequential streams like files or generators, not for the general handling of iterable objects. I will fix this later today.

**Comment by svirgilgood** [comment]
two questions: so  given `my_variable = "ninjaaron is a dork"`, `my_variable` is an iterable, but not an iterator? 

second: also, does the fix also need to account for python 3.8 and 3.9?

**Comment by svirgilgood** [comment]
@ninjaaron, Iterator is also in the `collections.abc` module. But this still probably doesn't address the issue of previous versions of the collections module.

**Comment by ninjaaron** [comment]
This should have the the desired behavior in old version of python going back to 3.3. Thanks for the contribution!

**Pull request merged**
